### ISSUE TITLE
Install c# 6.0 in VS2012

### ISSUE THREAD

**Issue by lyhlbyl** [ggrov/tacny#32]
1) Go to TOOL -> Extensions and Updates to double all are the latest version, in particular NuGet
2) Open **PM** from TOOL -> NGet Package Manager -> Package Manager Console
to install the 6.0 compiler by the 
`Install-Package Microsoft.Net.Compilers -Version 1.2.2`
Note that for each solution requiring c# 6.0 will need to install this package
3)  Right click solution to select **Manage NuGet Package for Solution**, then to apply the installed  package to all projects in the solution

**Comment by Tapanito** [comment]
Moved to readme
